version: "3.1"

services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./back/data_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

  backend:
    image: node
    container_name: api
    ports:
      - 3001:3001
    volumes:
      - ./back:/application/back
      - ./tsconfig.base.json:/application/tsconfig.base.json
    environment:
      MONGODB_URL: mongodb://root:example@mongo:27017/
      PORT: 3001
    working_dir: /application/back
    command: npm i && npm run dev
    depends_on:
      - mongo
